-- Hala Talab Partners - Stage 19: Orders
-- Safe migration: creates order tables without deleting existing data.

create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  customer_id uuid references auth.users(id) on delete set null,
  store_id uuid not null references public.stores(id) on delete cascade,
  driver_id uuid references auth.users(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending','accepted','preparing','ready','assigned','picked_up','delivered','cancelled','rejected')),
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  delivery_fee numeric(12,2) not null default 0 check (delivery_fee >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  payment_method text not null default 'cash',
  payment_status text not null default 'pending',
  customer_name text,
  customer_phone text,
  delivery_address text,
  notes text,
  accepted_at timestamptz,
  ready_at timestamptz,
  picked_up_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  product_name text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  total_price numeric(12,2) generated always as (quantity * unit_price) stored,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists orders_store_id_created_at_idx on public.orders(store_id, created_at desc);
create index if not exists orders_store_id_status_idx on public.orders(store_id, status);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Store owners can view own orders" on public.orders;
create policy "Store owners can view own orders"
on public.orders for select
to authenticated
using (
  exists (
    select 1 from public.stores
    where stores.id = orders.store_id
      and stores.owner_id = auth.uid()
  )
);

drop policy if exists "Store owners can update own orders" on public.orders;
create policy "Store owners can update own orders"
on public.orders for update
to authenticated
using (
  exists (
    select 1 from public.stores
    where stores.id = orders.store_id
      and stores.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.stores
    where stores.id = orders.store_id
      and stores.owner_id = auth.uid()
  )
);

drop policy if exists "Store owners can view own order items" on public.order_items;
create policy "Store owners can view own order items"
on public.order_items for select
to authenticated
using (
  exists (
    select 1
    from public.orders
    join public.stores on stores.id = orders.store_id
    where orders.id = order_items.order_id
      and stores.owner_id = auth.uid()
  )
);

-- Keep updated_at current.
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

-- Ask PostgREST to refresh the schema cache.
notify pgrst, 'reload schema';

-- Verification result.
select
  to_regclass('public.orders') as orders,
  to_regclass('public.order_items') as order_items;
