-- Hala Talab Partners — Stage 164
-- Push reliability + multi-device Store/Driver delivery.
-- Keeps store_notifications / driver_notifications as the single notification source.
-- Safe to re-run.

begin;

create extension if not exists pg_net;

-- Delivery audit: service-role Edge Function writes one row per FCM attempt.
-- Raw FCM tokens are deliberately NOT copied here.
create table if not exists public.push_delivery_attempts (
  id bigint generated by default as identity primary key,
  notification_id uuid not null,
  notification_table text not null check (notification_table in ('customer_notifications','store_notifications','driver_notifications')),
  recipient_user_id uuid not null,
  role text not null check (role in ('customer','business','driver')),
  token_id uuid null,
  platform text null,
  ok boolean not null default false,
  fcm_status integer null,
  response_excerpt text null,
  created_at timestamptz not null default now()
);

create index if not exists push_delivery_attempts_notification_idx
  on public.push_delivery_attempts(notification_table, notification_id, created_at desc);
create index if not exists push_delivery_attempts_recipient_idx
  on public.push_delivery_attempts(recipient_user_id, role, created_at desc);

alter table public.push_delivery_attempts enable row level security;
-- No client RLS policies: this is server-side diagnostic data only.

-- Reassert the canonical pg_net pipeline. Store/Driver in-app notifications
-- remain unchanged; every INSERT also queues one Edge Function invocation.
create or replace function public.hala_enqueue_store_notification_push()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, net
as $$
declare queued_request_id bigint;
begin
  select net.http_post(
    url := 'https://czoqxshblhgwanwsrudk.supabase.co/functions/v1/send-push',
    body := jsonb_build_object(
      'type', 'INSERT', 'table', 'store_notifications', 'schema', 'public',
      'record', jsonb_build_object('id', new.id), 'old_record', null
    ),
    headers := jsonb_build_object('Content-Type', 'application/json'),
    timeout_milliseconds := 5000
  ) into queued_request_id;
  return new;
exception when others then
  raise warning 'Hala Talab store push enqueue failed for notification %: %', new.id, sqlerrm;
  return new;
end;
$$;

create or replace function public.hala_enqueue_driver_notification_push()
returns trigger
language plpgsql
security definer
set search_path = public, extensions, net
as $$
declare queued_request_id bigint;
begin
  select net.http_post(
    url := 'https://czoqxshblhgwanwsrudk.supabase.co/functions/v1/send-push',
    body := jsonb_build_object(
      'type', 'INSERT', 'table', 'driver_notifications', 'schema', 'public',
      'record', jsonb_build_object('id', new.id), 'old_record', null
    ),
    headers := jsonb_build_object('Content-Type', 'application/json'),
    timeout_milliseconds := 5000
  ) into queued_request_id;
  return new;
exception when others then
  raise warning 'Hala Talab driver push enqueue failed for notification %: %', new.id, sqlerrm;
  return new;
end;
$$;

revoke all on function public.hala_enqueue_store_notification_push() from public;
revoke all on function public.hala_enqueue_driver_notification_push() from public;

drop trigger if exists hala_store_notifications_push on public.store_notifications;
create trigger hala_store_notifications_push
after insert on public.store_notifications
for each row execute function public.hala_enqueue_store_notification_push();

drop trigger if exists hala_driver_notifications_push on public.driver_notifications;
create trigger hala_driver_notifications_push
after insert on public.driver_notifications
for each row execute function public.hala_enqueue_driver_notification_push();

commit;

-- Final verification. orders_create_store_notification is the upstream source
-- used by a real Client order; hala_store_notifications_push is the external
-- Push hop. The first flag is informational because the existing in-app store
-- notification already proves an upstream order notification path is active.
select
  exists (select 1 from pg_extension where extname='pg_net') as pg_net_ready,
  to_regclass('public.device_push_tokens') is not null as push_tokens_ready,
  to_regclass('public.push_delivery_attempts') is not null as delivery_audit_ready,
  exists (
    select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
    where not t.tgisinternal and n.nspname='public' and c.relname='store_notifications'
      and t.tgname='hala_store_notifications_push' and t.tgenabled <> 'D'
  ) as store_push_trigger_ready,
  exists (
    select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
    where not t.tgisinternal and n.nspname='public' and c.relname='driver_notifications'
      and t.tgname='hala_driver_notifications_push' and t.tgenabled <> 'D'
  ) as driver_push_trigger_ready,
  exists (
    select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace
    where not t.tgisinternal and n.nspname='public' and c.relname='orders'
      and t.tgname='orders_create_store_notification' and t.tgenabled <> 'D'
  ) as client_order_to_store_notification_trigger_seen;
